platform :ios, '9.0'

#ignore all warnings from all pods
inhibit_all_warnings!

target 'cs571-hw9' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftyJSON'
pod 'Alamofire'
pod 'EasyToast'
pod 'SearchTextField'
pod 'SwiftSpinner'
pod 'FacebookShare'
pod 'FacebookCore'
pod 'FacebookLogin'

  # Pods for cs571-hw9

  target 'cs571-hw9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cs571-hw9UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
